## Project Description: Next Word Prediction Using LSTM
#### Project Overview:

This project aims to develop a deep learning model for predicting the next word in a given sequence of words. The model is built using Long Short-Term Memory (LSTM) networks, which are well-suited for sequence prediction tasks. The project includes the following steps:

1- Data Collection: We use the text of Shakespeare's "Hamlet" as our dataset. This rich, complex text provides a good challenge for our model.

2- Data Preprocessing: The text data is tokenized, converted into sequences, and padded to ensure uniform input lengths. The sequences are then split into training and testing sets.

3- Model Building: An LSTM model is constructed with an embedding layer, two LSTM layers, and a dense output layer with a softmax activation function to predict the probability of the next word.

4- Model Training: The model is trained using the prepared sequences, with early stopping implemented to prevent overfitting. Early stopping monitors the validation loss and stops training when the loss stops improving.

5- Model Evaluation: The model is evaluated using a set of example sentences to test its ability to predict the next word accurately.

6- Deployment: A Streamlit web application is developed to allow users to input a sequence of words and get the predicted next word in real-time.

In [1]:
## Data Collection
import nltk
nltk.download('gutenberg')

from nltk.corpus import gutenberg

# Correct book filenames
books = [
    'shakespeare-hamlet.txt',
    'shakespeare-macbeth.txt',
    'shakespeare-caesar.txt',
    'austen-emma.txt',
    'austen-sense.txt',
    'austen-persuasion.txt',
    'milton-paradise.txt',
    'melville-moby_dick.txt'
]

combined_text = ""

for book in books:
    combined_text += gutenberg.raw(book) + "\n\n"

with open('hamlet.txt', 'w', encoding='utf-8') as file:
    file.write(combined_text)

print("Corpus created successfully!")

Corpus created successfully!


[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\atulk\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [2]:
## Data Preprocessing

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

##laod the dataset
with open('hamlet.txt','r') as file:
    text=file.read().lower()

## Tokenize the text-creating indexes for words
tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])
total_words=len(tokenizer.word_index)+1
total_words



c:\Programs\Deep Learning\PROJECTS\Next Word Predictor-Using LSTM RNN\venv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


29115

In [3]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'a': 5,
 'in': 6,
 'i': 7,
 'it': 8,
 'that': 9,
 'was': 10,
 'his': 11,
 'her': 12,
 'not': 13,
 'he': 14,
 'with': 15,
 'as': 16,
 'be': 17,
 'for': 18,
 'but': 19,
 'you': 20,
 'she': 21,
 'is': 22,
 'had': 23,
 'all': 24,
 'at': 25,
 'so': 26,
 'him': 27,
 'by': 28,
 'have': 29,
 'on': 30,
 'this': 31,
 'from': 32,
 'my': 33,
 'they': 34,
 'no': 35,
 'or': 36,
 'which': 37,
 'me': 38,
 'what': 39,
 'very': 40,
 'their': 41,
 'would': 42,
 'were': 43,
 'could': 44,
 'one': 45,
 'been': 46,
 'there': 47,
 'more': 48,
 'will': 49,
 'them': 50,
 'now': 51,
 'when': 52,
 'if': 53,
 'are': 54,
 'an': 55,
 'do': 56,
 'such': 57,
 'your': 58,
 'we': 59,
 'mr': 60,
 'any': 61,
 'must': 62,
 'mrs': 63,
 'then': 64,
 'who': 65,
 'than': 66,
 'some': 67,
 'said': 68,
 'much': 69,
 'only': 70,
 'how': 71,
 'like': 72,
 'good': 73,
 'well': 74,
 'man': 75,
 'did': 76,
 'out': 77,
 'every': 78,
 'should': 79,
 'time': 80,
 'though': 81,
 'other': 82,
 'w

In [4]:
## create inoput sequences
input_sequences=[]
for line in text.split('\n'):
    token_list=tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequence=token_list[:i+1]
        input_sequences.append(n_gram_sequence)

        

In [5]:
input_sequences

[[1, 5833],
 [1, 5833, 4],
 [1, 5833, 4, 703],
 [1, 5833, 4, 703, 28],
 [1, 5833, 4, 703, 28, 1972],
 [1, 5833, 4, 703, 28, 1972, 7856],
 [1, 5833, 4, 703, 28, 1972, 7856, 12929],
 [4391, 10498],
 [4391, 10498, 10499],
 [4391, 10498, 10499, 6344],
 [292, 5834],
 [292, 5834, 2],
 [292, 5834, 2, 12930],
 [292, 5834, 2, 12930, 113],
 [292, 5834, 2, 12930, 113, 17172],
 [5834, 2303],
 [5834, 2303, 47],
 [5835, 763],
 [5835, 763, 404],
 [5835, 763, 404, 38],
 [5835, 763, 404, 38, 319],
 [5835, 763, 404, 38, 319, 7040],
 [58, 512],
 [2785, 117],
 [2785, 117, 1539],
 [2785, 117, 1539, 1],
 [2785, 117, 1539, 1, 252],
 [5835, 5834],
 [2785, 14],
 [5835, 20],
 [5835, 20, 116],
 [5835, 20, 116, 98],
 [5835, 20, 116, 98, 3005],
 [5835, 20, 116, 98, 3005, 478],
 [5835, 20, 116, 98, 3005, 478, 58],
 [5835, 20, 116, 98, 3005, 478, 58, 2786],
 [2785, 472],
 [2785, 472, 51],
 [2785, 472, 51, 17173],
 [2785, 472, 51, 17173, 7041],
 [2785, 472, 51, 17173, 7041, 303],
 [2785, 472, 51, 17173, 7041, 303, 14

In [6]:
## Pad Sequences
max_sequence_len=max([len(x) for x in input_sequences])
max_sequence_len

18

In [7]:
input_sequences=np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))
input_sequences

array([[   0,    0,    0, ...,    0,    1, 5833],
       [   0,    0,    0, ...,    1, 5833,    4],
       [   0,    0,    0, ..., 5833,    4,  703],
       ...,
       [   0,    0,    0, ..., 2927,  453,   70],
       [   0,    0,    0, ...,  453,   70,  189],
       [   0,    0,    0, ...,   70,  189,  213]],
      shape=(655331, 18), dtype=int32)

In [8]:
##create predicitors and label
import tensorflow as tf
x,y=input_sequences[:,:-1],input_sequences[:,-1]

In [9]:
x

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1, 5833],
       [   0,    0,    0, ...,    1, 5833,    4],
       ...,
       [   0,    0,    0, ...,   12, 2927,  453],
       [   0,    0,    0, ..., 2927,  453,   70],
       [   0,    0,    0, ...,  453,   70,  189]],
      shape=(655331, 17), dtype=int32)

In [10]:
y

array([5833,    4,  703, ...,   70,  189,  213],
      shape=(655331,), dtype=int32)

In [11]:
y = np.array(y) 

In [12]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [13]:
# Define early stopping
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

In [14]:
## Train our LSTM RNN

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout,GRU

## Define the model
model=Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation="softmax"))

# #Compile the model
model.compile(loss="sparse_categorical_crossentropy",optimizer='adam',metrics=['accuracy'])
model.build(input_shape=(None, max_sequence_len - 1))
model.summary()

c:\Programs\Deep Learning\PROJECTS\Next Word Predictor-Using LSTM RNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 17, 100)        │     2,911,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 17, 150)        │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 17, 150)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 100)            │       100,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 29115)          │     2,940,615 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,103,115 (23.28 MB)

 Trainable params: 6,103,115 (23.28 MB)

 Non-trainable params: 0 (0.00 B)

In [15]:
## Train the model
history=model.fit(x_train,y_train,epochs=50,
                  validation_data=(x_test,y_test),
                  verbose=1,
                  callbacks=[early_stopping]
                  )


Epoch 1/50
16384/16384 ━━━━━━━━━━━━━━━━━━━━ 713s 43ms/step - accuracy: 0.0757 - loss: 6.7141 - val_accuracy: 0.0984 - val_loss: 6.3997
Epoch 2/50
16384/16384 ━━━━━━━━━━━━━━━━━━━━ 647s 39ms/step - accuracy: 0.1041 - loss: 6.2199 - val_accuracy: 0.1096 - val_loss: 6.2970
Epoch 3/50
16384/16384 ━━━━━━━━━━━━━━━━━━━━ 628s 38ms/step - accuracy: 0.1135 - loss: 6.0347 - val_accuracy: 0.1147 - val_loss: 6.2322
Epoch 4/50
16384/16384 ━━━━━━━━━━━━━━━━━━━━ 628s 38ms/step - accuracy: 0.1196 - loss: 5.9102 - val_accuracy: 0.1174 - val_loss: 6.2018
Epoch 5/50
16384/16384 ━━━━━━━━━━━━━━━━━━━━ 603s 37ms/step - accuracy: 0.1245 - loss: 5.8129 - val_accuracy: 0.1210 - val_loss: 6.1813
Epoch 6/50
16384/16384 ━━━━━━━━━━━━━━━━━━━━ 645s 39ms/step - accuracy: 0.1291 - loss: 5.7291 - val_accuracy: 0.1237 - val_loss: 6.1832
Epoch 7/50
16384/16384 ━━━━━━━━━━━━━━━━━━━━ 611s 37ms/step - accuracy: 0.1328 - loss: 5.6568 - val_accuracy: 0.1249 - val_loss: 6.2101
Epoch 8/50
16384/16384 ━━━━━━━━━━━━━━━━━━━━ 609s 37ms/s

In [3]:
# Function to predict the next word

def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    token_list = token_list[-(max_sequence_len - 1):]

    token_list = pad_sequences(
        [token_list],
        maxlen=max_sequence_len - 1,
        padding='pre'
    )

    prediction = model.predict(token_list, verbose=0)
    predicted_index = np.argmax(prediction, axis=1)[0]

    return tokenizer.index_word.get(predicted_index, None)

In [ ]:
input_text = "To be not to be"
print(f"Input text:{input_text}")
max_sequence_len = model.input_shape[1]+1
next_word = predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word Prediction:{next_word}")

In [40]:
## Save the model
model.save("next_word_lstm.keras")
## Save the tokenizer
import pickle
with open('tokenizer.pickle','wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)

In [ ]:
## GRU RNN

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout,GRU

## Define the model
model=Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(GRU(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(GRU(100))
model.add(Dense(total_words,activation="softmax"))

# #Compile the model
model.compile(loss="sparse_categorical_crossentropy",optimizer='adam',metrics=['accuracy'])
model.build(input_shape=(None, max_sequence_len - 1))
model.summary()

In [ ]:
## Train the model
history=model.fit(x_train,y_train,epochs=50,
                  validation_data=(x_test,y_test),
                  verbose=1,
                  callbacks=[early_stopping]
                  )
